server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/filesystem?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 520131
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  config-location: classpath:SqlMapConfig.xml
  mapper-locations: classpath:mapperxml/*.xml
